# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilxel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
