from Sepia import Sepia
from OilPainting import OilPainting
from Comic import Comic
from Mosaic import Mosaic
from Pencil import Pencil
from Solarize import Solarize
from Molten import Molten
from Ice import Ice
from GlowingEdge import GlowingEdge
from Aqua import Aqua
from Pinch import Pinch
from PaperCut import PaperCut
